<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.03" os="" host="LAPTOP-7ORU2QJF"><DocLocation><![CDATA[C:\capgemini\DataDrivenFramework\Driver\Driver]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[Driver]]></DName>
<Res><![CDATA[Res45]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[tr1]]></Obj>
<Details plainTxt="False" ><![CDATA[Transaction "tr1" started.]]></Details>
<Time><![CDATA[30-03-2022 - 12:26:12]]></Time>
<TimeTick>1648623372</TimeTick>
<NodeArgs eType="Transaction" icon="5" nRep="8" nType="Start Transaction" Source="Action1" SourceLine="10" >
<Disp><![CDATA[tr1]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[30-03-2022 - 12:26:20]]></Time>
<TimeTick>1648623380</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run ""C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe"",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run ""C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe"",1]]></Details>
<Time><![CDATA[30-03-2022 - 12:26:20]]></Time>
<TimeTick>1648623380</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="12" status="Passed" >
<Disp><![CDATA[Run ""C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe"",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="11" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[30-03-2022 - 12:26:21]]></Time>
<TimeTick>1648623381</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[30-03-2022 - 12:26:21]]></Time>
<TimeTick>1648623381</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="17" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hp"]]></Details>
<Time><![CDATA[30-03-2022 - 12:26:22]]></Time>
<TimeTick>1648623382</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="19" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[30-03-2022 - 12:26:22]]></Time>
<TimeTick>1648623382</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="21" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[30-03-2022 - 12:26:22]]></Time>
<TimeTick>1648623382</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="22" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="16" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj ><![CDATA[Login]]></Obj>
<Details ><![CDATA[Login Successful]]></Details>
<Time><![CDATA[30-03-2022 - 12:26:22]]></Time>
<TimeTick>1648623382</TimeTick>
<NodeArgs eType="User" icon="10" nRep="23" status="Passed" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[30-03-2022 - 12:26:24]]></Time>
<TimeTick>1648623384</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[30-03-2022 - 12:26:24]]></Time>
<TimeTick>1648623384</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="26" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[30-03-2022 - 12:26:34]]></Time>
<TimeTick>1648623394</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="28" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="25" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj ><![CDATA[CloseApp]]></Obj>
<Details ><![CDATA[Closeapp unSuccessful]]></Details>
<Time><![CDATA[30-03-2022 - 12:26:34]]></Time>
<TimeTick>1648623394</TimeTick>
<NodeArgs eType="User" icon="10" nRep="29" status="Passed" >
<Disp><![CDATA[CloseApp]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[30-03-2022 - 12:26:36]]></Time>
<TimeTick>1648623396</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Run ""C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe"",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run ""C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe"",1]]></Details>
<Time><![CDATA[30-03-2022 - 12:26:36]]></Time>
<TimeTick>1648623396</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="33" status="Passed" >
<Disp><![CDATA[Run ""C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe"",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="32" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[30-03-2022 - 12:26:37]]></Time>
<TimeTick>1648623397</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[30-03-2022 - 12:26:37]]></Time>
<TimeTick>1648623397</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="39" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hp"]]></Details>
<Time><![CDATA[30-03-2022 - 12:26:38]]></Time>
<TimeTick>1648623398</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="41" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[30-03-2022 - 12:26:38]]></Time>
<TimeTick>1648623398</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="43" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[30-03-2022 - 12:26:38]]></Time>
<TimeTick>1648623398</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="44" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="38" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj ><![CDATA[Login]]></Obj>
<Details ><![CDATA[Login Successful]]></Details>
<Time><![CDATA[30-03-2022 - 12:26:38]]></Time>
<TimeTick>1648623398</TimeTick>
<NodeArgs eType="User" icon="10" nRep="45" status="Passed" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[30-03-2022 - 12:26:40]]></Time>
<TimeTick>1648623400</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[30-03-2022 - 12:26:40]]></Time>
<TimeTick>1648623400</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="48" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[30-03-2022 - 12:26:50]]></Time>
<TimeTick>1648623410</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="50" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="47" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj ><![CDATA[CloseApp]]></Obj>
<Details ><![CDATA[Closeapp unSuccessful]]></Details>
<Time><![CDATA[30-03-2022 - 12:26:50]]></Time>
<TimeTick>1648623410</TimeTick>
<NodeArgs eType="User" icon="10" nRep="51" status="Passed" >
<Disp><![CDATA[CloseApp]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[30-03-2022 - 12:26:52]]></Time>
<TimeTick>1648623412</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Run ""C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe"",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run ""C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe"",1]]></Details>
<Time><![CDATA[30-03-2022 - 12:26:52]]></Time>
<TimeTick>1648623412</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="55" status="Passed" >
<Disp><![CDATA[Run ""C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe"",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="54" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[30-03-2022 - 12:26:53]]></Time>
<TimeTick>1648623413</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[30-03-2022 - 12:26:53]]></Time>
<TimeTick>1648623413</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="61" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hp"]]></Details>
<Time><![CDATA[30-03-2022 - 12:26:54]]></Time>
<TimeTick>1648623414</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="63" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[30-03-2022 - 12:26:54]]></Time>
<TimeTick>1648623414</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="65" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[30-03-2022 - 12:26:54]]></Time>
<TimeTick>1648623414</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="66" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="60" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj ><![CDATA[Login]]></Obj>
<Details ><![CDATA[Login Successful]]></Details>
<Time><![CDATA[30-03-2022 - 12:26:54]]></Time>
<TimeTick>1648623414</TimeTick>
<NodeArgs eType="User" icon="10" nRep="67" status="Passed" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[30-03-2022 - 12:26:56]]></Time>
<TimeTick>1648623416</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[30-03-2022 - 12:26:56]]></Time>
<TimeTick>1648623416</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="70" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[30-03-2022 - 12:27:06]]></Time>
<TimeTick>1648623426</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="72" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="69" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj ><![CDATA[CloseApp]]></Obj>
<Details ><![CDATA[Closeapp unSuccessful]]></Details>
<Time><![CDATA[30-03-2022 - 12:27:06]]></Time>
<TimeTick>1648623426</TimeTick>
<NodeArgs eType="User" icon="10" nRep="73" status="Passed" >
<Disp><![CDATA[CloseApp]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[30-03-2022 - 12:27:25]]></Time>
<TimeTick>1648623445</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Run ""C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe"",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run ""C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe"",1]]></Details>
<Time><![CDATA[30-03-2022 - 12:27:25]]></Time>
<TimeTick>1648623445</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="77" status="Passed" >
<Disp><![CDATA[Run ""C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe"",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="76" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[30-03-2022 - 12:27:25]]></Time>
<TimeTick>1648623445</TimeTick>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[30-03-2022 - 12:27:25]]></Time>
<TimeTick>1648623445</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="83" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hp"]]></Details>
<Time><![CDATA[30-03-2022 - 12:27:26]]></Time>
<TimeTick>1648623446</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="85" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[30-03-2022 - 12:27:26]]></Time>
<TimeTick>1648623446</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="87" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[30-03-2022 - 12:27:26]]></Time>
<TimeTick>1648623446</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="88" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="82" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj ><![CDATA[Login]]></Obj>
<Details ><![CDATA[Login Successful]]></Details>
<Time><![CDATA[30-03-2022 - 12:27:26]]></Time>
<TimeTick>1648623446</TimeTick>
<NodeArgs eType="User" icon="10" nRep="89" status="Passed" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[30-03-2022 - 12:27:28]]></Time>
<TimeTick>1648623448</TimeTick>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[30-03-2022 - 12:27:28]]></Time>
<TimeTick>1648623448</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="92" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[30-03-2022 - 12:27:38]]></Time>
<TimeTick>1648623458</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="94" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="91" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj ><![CDATA[CloseApp]]></Obj>
<Details ><![CDATA[Closeapp unSuccessful]]></Details>
<Time><![CDATA[30-03-2022 - 12:27:38]]></Time>
<TimeTick>1648623458</TimeTick>
<NodeArgs eType="User" icon="10" nRep="95" status="Passed" >
<Disp><![CDATA[CloseApp]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[30-03-2022 - 12:27:40]]></Time>
<TimeTick>1648623460</TimeTick>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Run ""C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe"",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run ""C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe"",1]]></Details>
<Time><![CDATA[30-03-2022 - 12:27:40]]></Time>
<TimeTick>1648623460</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="99" status="Passed" >
<Disp><![CDATA[Run ""C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe"",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="98" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[30-03-2022 - 12:27:40]]></Time>
<TimeTick>1648623460</TimeTick>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[30-03-2022 - 12:27:40]]></Time>
<TimeTick>1648623460</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="105" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hp"]]></Details>
<Time><![CDATA[30-03-2022 - 12:27:41]]></Time>
<TimeTick>1648623461</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="107" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[30-03-2022 - 12:27:41]]></Time>
<TimeTick>1648623461</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="109" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[30-03-2022 - 12:27:41]]></Time>
<TimeTick>1648623461</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="110" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="104" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj ><![CDATA[Login]]></Obj>
<Details ><![CDATA[Login Successful]]></Details>
<Time><![CDATA[30-03-2022 - 12:27:41]]></Time>
<TimeTick>1648623461</TimeTick>
<NodeArgs eType="User" icon="10" nRep="111" status="Passed" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[30-03-2022 - 12:27:42]]></Time>
<TimeTick>1648623462</TimeTick>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[30-03-2022 - 12:27:42]]></Time>
<TimeTick>1648623462</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="114" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[30-03-2022 - 12:27:53]]></Time>
<TimeTick>1648623473</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="116" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="113" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj ><![CDATA[CloseApp]]></Obj>
<Details ><![CDATA[Closeapp unSuccessful]]></Details>
<Time><![CDATA[30-03-2022 - 12:27:53]]></Time>
<TimeTick>1648623473</TimeTick>
<NodeArgs eType="User" icon="10" nRep="117" status="Passed" >
<Disp><![CDATA[CloseApp]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[tr1]]></Obj>
<Details plainTxt="False" ><![CDATA[Transaction "tr1" ended with "Pass" status (Total Duration: 102.9560 sec).]]></Details>
<Time><![CDATA[30-03-2022 - 12:27:55]]></Time>
<TimeTick>1648623475</TimeTick>
<NodeArgs eType="Transaction" icon="11" nRep="118" nType="End Transaction" Source="Action1" SourceLine="103" >
<Disp><![CDATA[tr1]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="30-03-2022 - 12:26:12" eTime="30-03-2022 - 12:27:55" passed="15" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T67">
<AName><![CDATA[Action2]]></AName>
<Summary sTime="30-03-2022 - 12:27:55" eTime="30-03-2022 - 12:27:55" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="120" >
<Disp><![CDATA[Action2 Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T68">
<AName><![CDATA[Action3]]></AName>
<Summary sTime="30-03-2022 - 12:27:55" eTime="30-03-2022 - 12:27:55" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="122" >
<Disp><![CDATA[Action3 Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T69">
<AName><![CDATA[Action4]]></AName>
<Summary sTime="30-03-2022 - 12:27:55" eTime="30-03-2022 - 12:27:55" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="124" >
<Disp><![CDATA[Action4 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[Driver Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="30-03-2022 - 12:26:10" eTime="30-03-2022 - 12:27:56" passed="15" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Passed" >
<Disp><![CDATA[Test Driver Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>